# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Create jukebox group
  become_user: root
  become: true
  group: 
    name: "{{ jukebox_group }}" 

- name: Create docker group
  become_user: root
  become: true
  group: 
    name: "{{ docker_group }}" 

- name: Create jukebox user 
  become_user: root
  become: true
  user: 
    name: "{{ jukebox_user }}"
    groups: "{{ jukebox_group }}, {{docker_group}}" 
