# docker
- name: Copy over docker files
  copy:
    src: "files/"
    dest: "{{ build_dir }}/notebook"

- name: Copy over notebook & volume commands 
  template:
    src: "templates/{{ item }}"
    dest: "{{ run_dir }}/{{ item}}"
  with_items: [ "build_notebook", "build_volume" ]

- name: Run "{{ item }}" 
  shell: "warn=false chmod 755 {{ run_dir }}/{{ item }};cd {{ run_dir }};./{{ item }}"
  with_items: [ "build_notebook", "build_volume"]
