# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Remove the old hostname from ~/.ssh/known_hosts 
  shell: ssh-keygen -R "{{ inventory_hostname }}" -f ~/.ssh/known_hosts
  connection: local

- name: Add new hostname identity to the ~/.ssh/known_hosts file 
  shell: "ssh-keyscan jupyter >> ~/.ssh/known_hosts"
  connection: local
