# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Remove the old hostname from ~/.ssh/known_hosts 
  shell: ssh-keygen -R "{{ inventory_hostname }}" -f ~/.ssh/known_hosts
  connection: local

- name: Remove the old ip entry from ~/.ssh/known_hosts 
  shell: ssh-keygen -R "{{ host_ip }}" -f ~/.ssh/known_hosts
  connection: local

- name: Add new hostname identity to the ~/.ssh/known_hosts file 
  shell: "ssh-keyscan jupyter >> ~/.ssh/known_hosts"
  connection: local

- name: Copy over the ssh keys for everyone whose allowed to connect to this server 
  copy:
    src: ~/secrets/ssh/authorized_keys 
    dest: ~/.ssh/authorized_keys 
    force: yes
    mode: "u=rw,g=,o="
    owner: ubuntu
  when: creation_data.changed
