- name: Copy over jupyterhub icgc customizations for jupyterhub
  become_user: jupyterhub 
  become: true
  copy:
    src: "{{ item }}" 
    dest: "{{ home }}/share/jupyter/hub/templates/{{ item }}"
    owner: jupyterhub 
    mode: 0755
  with_items:
    - page.html
    - home.html
