# Configuration file for remote deployments
#
# Ansible Settings
host_key_checking: False 
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/ansible

# Jukebox Configuration 
# Which user will build and run Jukebox on the remote system, and  
# and where are the files to be stored?
jukebox_user: "jukebox"
jukebox_group: "jukebox"

# Name of the Jukebox service on the remote machine
jukebox_service_name: "{{ jukebox_user }}"

# where to install Jukebox
home: "~{{jukebox_user}}"

# The hostname of the system that Jukebox & Jupyterhub runs on
host: "jupyterhub.cancercollaboratory.org"
