###############################################################################
# Copyright 2017-2018(c) The Ontario Institute for Cancer Research. All rights reserved.
################################################################################
isLocal: true
host: localhost
home: ~/jukebox

# The settings below only works for machines with hostnames that are visible 
# across the entire Internet; if you're running this on your local machine,
# this probably isn't you.

# Use provided certs for SSL
use_certbot: false
use_oauth: true
use_ego: true
cert_dir: "../roles/jupyterhub/templates"

# We don't need to mount anything special for ssl 
config: ""
