###############################################################################
# Copyright 2017-2018(c) The Ontario Institute for Cancer Research. All rights reserved.
################################################################################
# To run a test version of Jupyterhub, set dev_mode to something like "-test",
# and switch to port 12345, which is only available from OICR machines.

secrets_file: '~/secrets/ansible_secrets.yml'
#dev_mode: "-test"
dev_mode: ""

jupyterhub_port: 443
#jupyterhub_port: 12345

# All Versions, Centralized for convenience.
# Cloudera
cloudera_major: 5
cloudera_version: "{{ cloudera_major }}.3.9"
cdh_version: "CDH{{ cloudera_major }}"
cdh_version_number: "{{ cloudera_version }}"
cm_version: "{{ cloudera_version }}"
cm_api_version: 9
security_groups: "Monitoring,jupyterhub,jupyterhub-test,default"

# Jupyterhub User setup 
jupyterhub_user: "jupyterhub{{ dev_mode }}"
jupyterhub_group: "jupyterhub{{ dev_mode }}"
jupyterhub_env: "jupyterhub"
jupyterhub_service: "{{ jupyterhub_user }}"
home: "/home/{{ jupyterhub_user }}"
jupyterhub_bin: "{{ home }}/bin"

# Jupyterhub Service configuration
jupyterhub_host: "jupyterhub.cancercollaboratory.org"

# Location of Jupyterhub service inside Docker
service_dir: "/srv/jupyterhub/"
cert_name: "secrets/cert.pem"
key_name: "secrets/cert.pem"
ssl_cert: "{{service_dir }}/{{cert_name}}"
ssl_key: "{{ service_dir }}/{{key_name}}"

# Jupyterhub Docker variables
jupyterhub_version: "0.8.0"
docker_machine_name: "{{ jupyterhub_user}}"
docker_network_name: "{{ jupyterhub_user}}-network"
# Name of the docker compose project  
compose_project_name: "{{ jupyterhub_user }}"
local_notebook_image: "{{ jupyterhub_user}}-notebook"
docker_notebook_image: "{{ jupyterhub_user}}-docker"

docker_notebook_dir: "/home/jovyan"
docker_spawn_cmd: "start-singleuser.sh"
data_volume: "{{ jupyterhub_user }}-data"
data_mount_point: /data
opt_volume: "{{ jupyterhub_user}}-opt"
web_mount_point: "/opt/conda/"
path: "/opt/conda/bin:/usr/bin:/usr/local/bin:/usr/sbin:/bin:/icgc/bin"
logo_path: "{{ service_dir }}/www_custom/hub/logo"
create_volume_image: "{{ jupyterhub_user }}-create_volume"
core_image: "{{ jupyterhub_user }}-core"
container_name: "jd{{dev_mode}}"

# Docker task currently symlinks these from the certbot files defined below
key_file: "~/secrets/ssl/privkey.pem"
cert_file: "~/secrets/ssl/cert.pem"

# Docker
docker_group: docker
oauthenticator_lib: "{{ home }}/lib/python3.5/site-packages/oauthenticator/"

# Google Client Id
#oauth_client_id: ''      # set this from the secrets file
#oauth_client_secret: ''  # set this from the secrets file

# Daco
#daco_base_url: '' # set this in the secrets file
#daco_client_key: '' # set this in the secrets file
#daco_client_secret: '' # set this in the secrets file
#daco_token: '' # set this in the secrets file
#daco_token_secret: '' # set this in the secrets file

# Need to point external DNS to point this hostname 
# to the floating ip address of our host
oauth_callback_url: "https://{{ jupyterhub_host }}:{{ jupyterhub_port }}/hub/oauth_callback"

# SSL Client Certificate Information
certbot_cert: /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/cert.pem
certbot_key: /etc/letsencrypt/live/jupyterhub.cancercollaboratory.org/privkey.pem
certbot_email: kevin.hartmann@oicr.on.ca
# OpenStack Settings
auth_url: https://console.cancercollaboratory.org:5000/v3/
login_project_name: OICR_Ferretti_Jupyter
#login_username: '' # set in secrets file
#login_password: '' # set in secrets file
private_net: host-10-10-0-3.collab.org
image_id: Ubuntu 18.04 - latest
flavor_id: c1.large
internal_network_name: "OICR_Ferretti_Jupyter_net"
ip_pool: "ext-net"

# Ansible Settings
host_key_checking: False 
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/ansible
