# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.
# Our debian installation has python3, not python2
- name: Ensure we have python2 so we can run ansible modules 
  gather_facts: no
  become: yes
  hosts: "{{ group }}"
  remote_user: "{{ ansible_ssh_user }}"
  vars_files:
    - "../vars/main.yml"
    - "../vars/deploy.yml"
  tasks:
    - ping:
      register: ping 
      ignore_errors: true

    - name: "Update apt"
      raw: sudo apt-get update
      when: ping.failed

    - name: "Install python"
      raw: yes | sudo apt-get install python
      # remote_user: "{{ ansible_ssh_user }}"
      when: ping.failed
