# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Setup Jukebox on localhost 
  hosts: "{{ group }}" 
  vars_files:
    - "../vars/main.yml"
    - "../vars/local.yml"
    - "../vars/jukebox.yml"
    - "../vars/docker.yml"
    - "../vars/docker_local.yml"
    - "../vars/jupyterhub.yml"
    - "../vars/jupyter_notebook.yml"
    - "../vars/oauth.yml"
    - "../vars/ego.yml"
    - "{{ oauth_secrets }}"
    - "{{ ego_secrets }}"
  roles: 
    - "../roles/jukebox"
  connection: local
