# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Setup jupyterhub for localhost 
  hosts: "{{ group }}" 
  vars_files:
    - "../vars/main.yml"
    - "{{ secrets_file }}"
  roles: 
    - "../roles/docker"
  connection: local
