# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: "Make secrets directory: {{ ssl_dir }}"
  shell: "test -d {{ ssl_dir }} || mkdir -p {{ ssl_dir }}"

- name: "Make config directory: '{{ config_dir }}'"
  shell: "test -d {{ config_dir }} || mkdir -p {{ config_dir }}"

- name: Copy over docker files 
  copy: 
    src: "docker/"
    dest: "{{ home }}" 

- name: "Make share directory: '{{ share_dir }}'"
  shell: "test -d {{ share_dir }} || mkdir -p {{ share_dir }}"

#- name: "Copy over docker files to build directory: '{{ build_dir }}'" 
#  copy: 
#    src: "docker/build"
#    dest: "{{ build_dir }}" 

- name: Copy over our oauth secrets template into the secrets directory
  template: 
    src: oauth.env
    dest: "{{ oauth_env }}"
    owner: "{{ jukebox_user }}"
  when: use_oauth

- name: Copy over blank oauth secrets file into the secrets directory
  copy: 
    src: "oauth_env.empty"
    dest: "{{ oauth_env }}"
  when: not use_oauth

- name: Put our jupyterhub service authentication into "dev" mode if not using oauth
  set_fact:
    dev_mode: "set"
  when: not use_oauth

- name: "Copy over our environment variables file: '{{ jukebox_env }}'" 
  template: 
    src: jukebox.env 
    dest: "{{ jukebox_env }}"
  when: isLocal

- name: "Copy over our environment variables file: '{{ jukebox_env }}'" 
  template: 
    src: jukebox.env 
    dest: "{{ jukebox_env }}"
    owner: "{{ jukebox_user }}"
  when: not isLocal

- name: Copy our certbot cert on our remote host to it's proper SSL directory
  become: true
  become_user: "{{ jukebox_user }}"
  shell: "cp {{ certbot_cert }} {{ certbot_key }} {{ ssl_dir }}"
  when: use_certbot

- name: Copy default certs into our ssl directory
  copy: 
    src: "{{ item }}"
    dest: "{{ ssl_dir }}"
  when: isLocal 
  with_items: ["cert.pem","privkey.pem"]

- name: "Copy over our docker-compose file to our run directory: '{{ run_dir }}'"
  copy: 
    src: "docker/bin/"
    dest: "{{ run_dir }}"

- name: "Copy over our shell script templates to our run directory: '{{ run_dir }}'"
  template: 
    src: "{{ item }}"
    dest: "{{ run_dir }}"
  with_items: ['build.sh','reset.sh']
- name: Set permissions on our build file
  shell: "warn=false chmod 755 {{ run_dir }}/*.sh"

- name: Build docker image 
  shell: "{{ run_dir }}/build.sh"
