# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Make docker & ssl secrets directory
  shell: "test -d {{ home }}/secrets/ssl || mkdir -p {{ home }}/secrets/ssl"

- name: Make docker & ssl config directory
  shell: "test -d {{ home }}/config || mkdir -p {{ home }}/config/"

- name: Copy over docker files 
  copy: 
    src: "docker/"
    dest: "{{ home }}/docker/" 

- name: Copy over our oauth secrets template into the secrets directory
  template: 
    src: jupyterhub_oauth.env
    dest: "{{ home }}/secrets/jupyterhub_oauth.env"
    owner: "{{ jupyterhub_user }}"

- name: Copy over our environments template file to docker/hub 
  template: 
    src: jupyterhub.env 
    dest: "{{ home }}/config/jupyterhub.env"
    owner: "{{ jupyterhub_user }}"

- name: Copy our certbot cert into our secrets directory
  become: true
  become_user: "{{ jupyterhub_user }}"
  shell: "cp {{ certbot_cert }} {{ home }}/secrets/ssl/"
  ignore_errors: true

- name: Copy our certbot key into our secrets directory
  become: true
  become_user: "{{ jupyterhub_user }}"
  shell: "cp {{ certbot_key }} {{ home }}/secrets/ssl/" 
  ignore_errors: true

- name: Set permissions on our build file
  shell: warn=false chmod 755 "{{ home }}/docker/build.sh"

- name: Build docker image 
  command: "{{ home }}/docker/build.sh"
