# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Make local docker & ssl secrets directory
  shell: "test -d ~/secrets/ssl || mkdir -p ~/secrets/ssl"

- name: Make local docker & ssl config directory
  shell: "test -d ~/config || mkdir -p ~/config/"

- name: Copy over docker files to ~/docker
  copy: 
    src: "docker/"
    dest: "~/docker/" 

- name: Copy over our oauth secrets template into the secrets directory (edit it, and rename it to jupyterhub_oauth.env)
  template: 
    src: jupyterhub_oauth.env
    dest: "~/secrets/jupyterhub_oauth.env_template"

- name: Copy over our environments template file to docker/hub (edit & rename it, too) 
  template: 
    src: jupyterhub.env 
    dest: "~/config/jupyterhub.env_template"

- name: Set permissions on our build file
  shell: warn=false chmod 755 ~/docker/build.sh

- name: Build docker image 
  command: "echo edit the files as described above, then run ~/docker/build.sh"
