- name: Install dockerhub 
  import_tasks: install.yml
  when: not isLocal 

- name: Build the dockerhub image 
  import_tasks: build.yml
  when: not isLocal 

- name: Run docker build locally
  import_tasks: build.yml
  connection: local
  when: isLocal 
