- name: "Make ssl secrets directory: {{ ssl_dir }}"
  shell: "test -d {{ ssl_dir }} || mkdir -p {{ ssl_dir }}"
  when: use_certbot

- name: Copy our certbot cert on our remote host to it's proper SSL directory
  become: true
  become_user: "{{ jukebox_user }}"
  shell: "cp {{ certbot_cert }} {{ ssl_dir }}/{{ ssl_cert }}"
  when: use_certbot

- name: Copy our certbot key on our remote host to it's proper SSL directory
  become: true
  become_user: "{{ jukebox_user }}"
  shell: "cp {{ certbot_key }} {{ssl_dir }}/{{ ssl_key}}"
  when: use_certbot
