# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Create a virtual environment 
  shell: "python3 -mvenv {{ home }}"

- name: Upgrade the version of pip inside the virtual environment 
  shell: ". {{ home }}/bin/activate; pip install --upgrade pip" 

- name: Install python packages into our virtual environment
  shell: ". {{ home }}/bin/activate; pip install jupyter sudospawner dockerspawner oauthenticator requests_oauthlib overture-song icgc" 
  
