# Copyright 2018(c) The Ontario Institute for Cancer Research. All rights reserved.
- name: Create the run directory if it doesn't exist
  shell: test -d {{ run_dir }} || mkdir -p {{ run_dir }}

- name: Create the config directory if it doesn't exist
  shell: test -d {{ config_dir }} || mkdir -p {{ config_dir }}
  when: use_certbot

- name: "Make a share directory: '{{ share_dir }}'"
  shell: "test -d {{ share_dir }} || mkdir -p {{ share_dir }}"

- name: "Make configuration directory: {{ config_dir }}"
  shell: "test -d {{ config_dir }} || mkdir -p {{ config_dir }}; touch {{ config_dir }}/ansible"

- name: Copy over our config file with all the ansible variables set
  template:
     src: "templates/jupyterhub_config.py"
     dest: "{{ config_dir }}"

- name: "Pull jupyterhub image"
  shell: "docker pull {{ jupyterhub_image }}"
  when: not isLocal

- name: Copy over certs and setup config files so SSL will work locally
  shell: "cp {{cert_dir}}/*.pem {{ config_dir }}"
  when: isLocal

- name: "Build jupyterhub image - {{ jupyterhub_image }}"
  shell: docker build -t "{{jupyterhub_image}}" "{{docker_file}}"
  when: isLocal
